package unmarshal

import "encoding/json"

//RawText Autogenerated by JSON-to-Go(https://mholt.github.io/json-to-go/),a very nice tool.
type RawText struct {
	Sentences []struct {
		Trans   string `json:"trans"`
		Orig    string `json:"orig"`
		Backend int    `json:"backend"`
	} `json:"sentences"`
	Src        string  `json:"src"`
	Confidence float64 `json:"confidence"`
	Spell      struct {
	} `json:"spell"`
	LdResult struct {
		Srclangs            []string  `json:"srclangs"`
		SrclangsConfidences []float64 `json:"srclangs_confidences"`
		ExtendedSrclangs    []string  `json:"extended_srclangs"`
	} `json:"ld_result"`
}

//Convert json2string.
func (r *RawText) Convert(data []byte) string {
	json.Unmarshal(data, r)
	return r.Sentences[0].Trans
}
